# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(817, 538)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 821, 491))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: purple;\n"
"}")
        self.widget.setObjectName("widget")
        self.label_banner = QtWidgets.QLabel(self.widget)
        self.label_banner.setGeometry(QtCore.QRect(280, -10, 411, 121))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_banner.setFont(font)
        self.label_banner.setStyleSheet("QLabel {\n"
"    color: lightgreen;\n"
"}")
        self.label_banner.setObjectName("label_banner")
        self.play_btn = QtWidgets.QPushButton(self.widget)
        self.play_btn.setGeometry(QtCore.QRect(260, 420, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.play_btn.setFont(font)
        self.play_btn.setStyleSheet("QPushButton {\n"
"    color: lightgreen;\n"
"    border: 3px solid lightgreen;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: lightgreen;\n"
"    color: black;\n"
"}")
        self.play_btn.setObjectName("play_btn")
        self.pause_btn = QtWidgets.QPushButton(self.widget)
        self.pause_btn.setGeometry(QtCore.QRect(510, 420, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pause_btn.setFont(font)
        self.pause_btn.setStyleSheet("QPushButton {\n"
"    color: lightgreen;\n"
"    border: 3px solid lightgreen;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: lightgreen;\n"
"    color: black;\n"
"}")
        self.pause_btn.setObjectName("pause_btn")
        self.stop_btn = QtWidgets.QPushButton(self.widget)
        self.stop_btn.setGeometry(QtCore.QRect(10, 420, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.stop_btn.setFont(font)
        self.stop_btn.setStyleSheet("QPushButton {\n"
"    color: lightgreen;\n"
"    border: 3px solid lightgreen;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: lightgreen;\n"
"    color: black;\n"
"}")
        self.stop_btn.setObjectName("stop_btn")
        self.mylist = QtWidgets.QListWidget(self.widget)
        self.mylist.setGeometry(QtCore.QRect(10, 100, 751, 301))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.mylist.setFont(font)
        self.mylist.setStyleSheet("QListWidget {\n"
"    color: #90ee90;\n"
"    border: 1px solid rgb(239, 115, 255);;\n"
"    border-radius: 5px;\n"
"}")
        self.mylist.setObjectName("mylist")
        self.label_path = QtWidgets.QLabel(self.widget)
        self.label_path.setGeometry(QtCore.QRect(10, 80, 751, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(10)
        self.label_path.setFont(font)
        self.label_path.setStyleSheet("QLabel {\n"
"    color: #90ee90;\n"
"}")
        self.label_path.setObjectName("label_path")
        self.sound_slider = QtWidgets.QSlider(self.widget)
        self.sound_slider.setGeometry(QtCore.QRect(780, 100, 31, 291))
        self.sound_slider.setStyleSheet("")
        self.sound_slider.setMaximum(100)
        self.sound_slider.setSingleStep(5)
        self.sound_slider.setProperty("value", 30)
        self.sound_slider.setOrientation(QtCore.Qt.Vertical)
        self.sound_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sound_slider.setTickInterval(5)
        self.sound_slider.setObjectName("sound_slider")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 817, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.about_action = QtWidgets.QAction(MainWindow)
        self.about_action.setObjectName("about_action")
        self.select_folder = QtWidgets.QAction(MainWindow)
        self.select_folder.setObjectName("select_folder")
        self.exit_action = QtWidgets.QAction(MainWindow)
        self.exit_action.setObjectName("exit_action")
        self.open_file_action = QtWidgets.QAction(MainWindow)
        self.open_file_action.setObjectName("open_file_action")
        self.menuFile.addAction(self.select_folder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.exit_action)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_banner.setText(_translate("MainWindow", "Music Player"))
        self.play_btn.setText(_translate("MainWindow", "Play"))
        self.pause_btn.setText(_translate("MainWindow", "Pause"))
        self.stop_btn.setText(_translate("MainWindow", "Stop"))
        self.mylist.setSortingEnabled(True)
        self.label_path.setText(_translate("MainWindow", "Folder: "))
        self.menuFile.setTitle(_translate("MainWindow", "&Files"))
        self.about_action.setText(_translate("MainWindow", "About"))
        self.select_folder.setText(_translate("MainWindow", "&Select Folder"))
        self.exit_action.setText(_translate("MainWindow", "&Exit"))
        self.open_file_action.setText(_translate("MainWindow", "&Open Files"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
